### ISSUE TITLE
[FEAT] The reviewer should be able to submit a review to the submitter

### ISSUE THREAD

**Issue by yeskunall** [yeskunall/pproval.app#14]
**Is your feature request related to a problem? Please describe.**

The `Editor` should be able to assign an article for review to a `Reviewer`

**Describe the solution you'd like**

__TODO__: Fill this in

**Acceptance criteria**

- [ ] Create `Reviewer` entity
- [ ] Create `ReviewerRepository` entity
- [ ] Create `submit-review` (_upload submission_) view
- _... Fill more as requirements keep coming in_

**Additional context**

N/A
