### ISSUE TITLE
[FEAT] The submitter should be able to upload a file for review

### ISSUE THREAD

**Issue by yeskunall** [yeskunall/pproval.app#5]
**Is your feature request related to a problem? Please describe.**

The `Submitter` should be able to upload a file to the server for review. In our case, this is replaced with a text box on the submission page that the submitted can copy text into.

**Describe the solution you'd like**

For now, the user should be able to write/copy the contents of a text file into the text box, and then be redirected to a “view” that renders the contents of the submission.

**Acceptance criteria**

- [ ] Create a `User` entity
- [ ] Create `UserRepository`
- [ ] Create `view` (_view submission_) view (Issue #8 )
- [ ] Create `upload` (_upload submission_) view (Issue #12 )
- [ ] Set up database to store file uploads (@yeskunall, tracking in #11)

**Additional context**

~How are we going to store the file? We need to investigate this~
PostgreSQL hosted on Heroku?

**Comment by yeskunall** [comment]
These instructions are a bit heavy, please bear with me

@PragyaJollySingh @RobynVG @ryanribeiro for each of the items in the acceptance criteria:

1. Create a separate issue. Assign it to yourself. Mark it as taken (just check the box in this issue)
2. Work on your issue after the midterm today evening
	1. Be quick to add unit tests for whatever you’re working on (_we need this so we can show some form of tests passing on the CI servers_)
3. Make a PR as soon as possible (_we really don’t have much time to work on this_)

Each milestone is worth 10%, and we don’t have much to show for the GitHub repo, so I’m just trying to get us rolling here as well.

@PragyaJollySingh @RobynVG since you two have already partially worked on this, you are more than welcome to use the existing code and incorporate it into our codebase.

**Comment by yeskunall** [comment]
@ryanribeiro this has been in progress for 19 days now. Can you please provide an update on this here?

If it is not currently being tackled, please move this to its appropriate column.

**Comment by ryanribeiro** [comment]
It is still in progress, just haven't gotten on top of it lately due to deadlines. It'll be worked on today.
